import { Inter } from "next/font/google";
import Head from "next/head";
import "./globals.css";
import "../../public/favicon.png";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Suitmedia Test",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon.png" />
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
